---
title: "2019-05-15 Lillian"
output: html_notebook
---

```{r}
Mat1 <- matrix(
  c(1:6), 2,3
)
Mat1
```

```{r}
class(Mat1)
typeof(Mat1)
```
```{r}
Mat2 <- matrix(
  c("a","b","c","d"), 2, 2
)
Mat2
```
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```
```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```
```{r}
class(StuDF$姓名)

StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```
```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3

class(StuDF3)
StuDF3
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```
```{r}
class(StuDF)
typeof(StuDF)
```
```{r}
LETTERS # R內設元素值為英文字母群的character vector
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```
```{r}
chosenLETTERS[8]
matObj1[8]
```
```{r}
matObj1
matObj1[3,2] 
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
```
```{r}
StuDF
StuDF[c("姓名","成績")] 
StuDF[1:5,c("姓名","成績")] 
```
```{r}
StuDF[,c("姓名","成績")]
```
```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```
```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```
```{r}
Mat1
names(Mat1) 
names(Mat1) <- letters[1:6]
names(Mat1)
```
```{r}
matObj1
colnames(matObj1) 
rownames(matObj1)
colnames(matObj1) <-c('欄位1','欄位2','欄位3')
colnames(matObj1)
matObj1
```
```{r}
rownames(matObj1) <- c('行：1','行：2','行：3','行：4','行：5')
matObj1
```



```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE,
  c("新元素","二元素")
)
```
```{r}
b
b[[3]]<- "false"
  b[[5]]<- "7"
  
b
b$元素3<-"false"

```
```{r}
b$元素
b[4]
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```
```{r}
library(lubridate)
time3<- exData3$期間
time3<- ymd(time3)
time3-> exData3$期間

class(exData3$期間)
```
```{r}
exData3$期間<- ymd(exData3$期間)
class(exData3$期間)
```
```{r}
isAsiaCrisis <- exData3$期間>=1997-06-01 &exData3$期間<=1998-12-01
isAsiaCrisis

錯了!時間沒有加ymd就只是字串
```
```{r}
isAsiaCrisis <- exData3$期間>=ymd("1997-06-01") &exData3$期間<=ymd("1998-12-01")
isAsiaCrisis
```

8.1.2
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```
```{r}
log <- transcriptDataFinal$學號=="92aS67fee"
 transcriptDataFinal[log,]
```

```{r}
supply_fun<- function(a,b,P){Qs<-a+b*P
return(Qs)
}
demand_fun <- function(c,d,P){
  Qd <- c-d*P
  return(Qd)
}
```



