---
title: '2019-04-10'
author: "林茂廷"
date: "4/10/2019"
output: html_document
---
練習
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#下在stringr
```{r}
library(stringr)
```
```{r}
install.packages("stringr")
```
#str_subse 抓出全部資料裡面包含你要找的資料
```{r}
course <- c("個體經濟學","投資學","總體經濟學")
str_subset(course,"經濟學")
str_detect(course,"經濟學")
```
```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
```
```{r}
str_subset(studentID,5,6)
```
#取出第A到B內的字元
```{r}
系別<-str_sub(studentID,5,6)
系別
入學年<-str_sub(studentID,2,4)
入學年


```
#向量概念 表示日期str_c
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
```
最後的結果為str_c抓出的答案
```{r}
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)

```


還有兩種簡化的寫法
```{r}

str_c(month,c("月"),day,c("日"))

str_c(month,"月",day,"日")
```
也可以加分隔符號(自己定義)
```{r}
month
day
str_c(month,day, sep="-")
```
#str_split()
```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```
#str_replace()
```{r}
dates
str_replace(dates,"-","月")
```
#str_replace_all()
若沒有all str_replace()只會把她遇到的第一個目標換掉 
```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```
```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```
```{r}
https://github.com/tpemartin/107-2-inclass-practice
```
```{r}
"https://github.com"
username
reponame
str_c("https://github.com",username[1:4],reponame[1:4])
```
#綜合練習1
```{r}
民國年月<-c ("099/01","099/02","099/03")
民國年月+ years(1911)
```
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
birthday
y<-str_sub(birthday,1,4)
m<-str_sub(birthday,5,6)
d<-str_sub(birthday,7,8)
bday<-str_c("西元",y,"年",m,"月",d,"日")
bday
```


```{r}
民國年月<-c("099/01","099/02","099/03")
str_sub(民國年月)
as.integer(099)
y<-99
y+


```
```{r}
民國年月<-c("099/01","099/02","099/03")
y<- str_sub(民國年月,2,3)
m<- str_sub(民國年月,5,6)
y2<- as.integer(y)
m2<- as.integer(m)
str_c("西元",y2+1911,"年",m2,"月")
```
```{r}
民國年月<-c("099/01","099/02","099/03")
y<-str_sub(民國年月,2,3)
y1<-as.integer(y)
m<-str_sub(民國年月,5,6)
m1<-as.integer(m)
str_c("西元",y1+1911,"年",m2,"月")
```
#list