---
title: "0424 practice"
output: html_notebook
---




```{r}
Mat1 <- matrix(
  c(1:6), 2,3
)
Mat1
```
```{r}
Mat1 <- matrix(
  c(1:6), 3,2
)
Mat1
```

```{r}
class(Mat1)
typeof(Mat1)
```
```{r}
Mat2 <- matrix(
  c("a","b","c","d"), 2, 2
)
Mat2
```
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```
```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
ans <-StuDF[[2]][[3]]
ans <-StuDF[["姓名"]][[3]]
ans
```
```{r}
class(StuDF$姓名)
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```
```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 

```
```{r}
as.data.frame(StuList) -> StuDF3

class(StuDF3)
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
```
```{r}
chosenLETTERS <- LETTERS[1:15]
chosenLETTERS
chosenletters <- letters[1:15]
chosenletters
```
```{r}
matObj1 <-matrix(chosenLETTERS,5,3)
matObj1 
matObj11 <-matrix(chosenLETTERS,3,5)
matObj11 
```
#tolower(m) # 轉成小寫
m
#toupper(m) # 轉成大寫
m
```{r}
matObj1
matObj1[[8]]
matObj1[[3,2]]
matObj1[3,2]

```
```{r}
matObj1[c(1,4),c(2,3)]
matObj1 <- matObj1[c(T,F,F,F,T),c(F,T,T)]
matObj1
```




