---
title: "2019-06-12"
output: html_notebook
---

```{r}
load(url("https://www.dropbox.com/s/duh5aaqgl2f5m3z/loopTranscriptData.Rda?raw=1"))
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
studentIds5 <- studentIds[1:5] # 前5筆學號
```
```{r}
for(i in studentIds5){ 
  print(i) 
}
```


```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```
```{r}
i <- 1
print(studentIds5[[i]])
```

```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```
```{r}
##sequence source
##body
##for loop
library(stringr)
for (i in seq_along(gmailAddress)) {
  if(str_detect(gmailAddress[i],"@gmail.com")){
    print(gmailAddress[i])
  }else{
    print(str_c(gmailAddress[i],"@gmail.com"))
  }
}
```
```{r}
# 開始設定
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
cat("起始狀況\n")
gmailAddress

# for loop
for(i in seq_along(gmailAddress)){
  if(!str_detect(gmailAddress[[i]],"@gmail.com")){
    correctGmailAddress <-
      str_c(gmailAddress[[i]],"@gmail.com")
    gmailAddress[[i]] <- correctGmailAddress
  }
}

cat("修正後狀況\n")
gmailAddress
```

任務一：存下來每個commit的author。

```{r}

load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```

0. saving container
```{r}
saveCommitAuthor <-
  vector("character",length(commitHistory))
```

1. sequence source
```{r}
commitHistory
```
2. body
```{r}
存下來「第i個」commit的author。

i<- 1

commitHistory[[i]]$commit$author$name -> saveCommitAuthor[[i]]
```
檢查一下
```{r}
saveCommitAuthor
```
3. for loop
```{r}
saveCommitAuthor <-
  vector("character",length(commitHistory)) # 0.
for(i in seq_along(commitHistory)){
  commitHistory[[i]]$commit$author$name -> saveCommitAuthor[[i]]
}
saveCommitAuthor
```