---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##下載lubridate套件
```{r}
library(lubridate)
```
##定義不同地區的時間
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
```
```{r}
twDateTime <- ymd_hms("2019-03-27 15:33:00", tz="Asia/Taipei")
```
```{r}
LisbonDateTime<-with_tz(twDateTime,tzone ="Europe/Lisbon")

```
```{r}
twDateTime<-ymd_hms("2019-03-27 15:00:00",tz="Asia/Taipei" )

twDateTime
```
```{r}
LisbonDateTime<- with_tz(twDateTime, tzone = "Europe/Lisbon")

LisbonDateTime
```
##換算當地時間成秒數
```{r}
typeof(twDateTime)
as.double(twDateTime)
```
```{r}
typeof(LisbonDateTime)
as.double(LisbonDateTime)
```
##Google 不同時間的表示法轉換成R看得懂得語言
```{r}
ymd("2018-09-11")
```
```{r}
mdy("03-03-2019")
```
```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
class(dtObject)
typeof(dtObject)
as.double(dtObject)
```
```{r}
as.integer(ymd('1998-02-02'))
as.integer(ymd("1998-02-03"))
```
##定義 並+-*
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```

```{r}
class(a+bL)
class(a-bL)
class(a*bL)
class(aL+bL)
a-aL
a-b
aL-b
a*b
a+b

```

```{r}
dtObject+1
```
```{r}
c<- ymd("2019-01-01")
d<- ymd("2019-01-03")
class(c)
class(d)
c-d
```

```{r}
cQ<- ymd_hms("2019-03-03 00:00:10")
dQ<- ymd_hms("2019-03-03 00:00:40")
class(cQ)
class(dQ)
cQ-dQ
```
```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)

```
```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```
##relational

```{r}
x<-5
y<-7
xx<-c(1,2,6)
yy<-c(4,5,3)

x<y
x==y

xx<=yy
xx!=yy
xx>=yy
xx>yy

```
## A%in%B 看一物是否與另一範圍有交集
它的意義是檢查A向量是否在B集合裡
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```
##文字也可以看集合
```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```
##缺失資料 NA無法作比較
```{r}
x6 <- c(1,NA,10)
y6 <- c(-1,NA,20)
x6==y6

```
#用is.na()找出缺失資料
```{r}
x6 <- c(1,NA,10)
y6 <- c(-1,NA,20)
is.na(x6)
is.na(y6)
x6==y6

```


